### ISSUE TITLE
Example "3rd Party Libararies" does not work

### ISSUE THREAD

**Issue by jhgg** [mikechau/react-primer-draft#10]
https://github.com/mikechau/react-primer-draft#react-and-3rd-party-libraries 

The DataTable example does not work at: http://jsbin.com/hapubiceta/4/edit?js,output

Getting an error in the console:

``````
Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
runner-3.25.22.min.js:1 error Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
    at invariant (http://dragon.ak.fbcdn.net/hphotos-ak-xfp1/t39.3284-6/10734339_319998684865598_389562622_n.js:18683:15)
    at Object.ReactMount._registerComponent (http://dragon.ak.fbcdn.net/hphotos-ak-xfp1/t39.3284-6/10734339_319998684865598_389562622_n.js:11746:39)
    at Object.<anonymous> (http://dragon.ak.fbcdn.net/hphotos-ak-xfp1/t39.3284-6/10734339_319998684865598_389562622_n.js:11790:36)
    at Object.wrapper [as _renderNewRootComponent] (http://dragon.ak.fbcdn.net/hphotos-ak-xfp1/t39.3284-6/10734339_319998684865598_389562622_n.js:12914:21)
    at Object.ReactMount.render (http://dragon.ak.fbcdn.net/hphotos-ak-xfp1/t39.3284-6/10734339_319998684865598_389562622_n.js:11863:32)
    at Object.wrapper [as render] (http://dragon.ak.fbcdn.net/hphotos-ak-xfp1/t39.3284-6/10734339_319998684865598_389562622_n.js:12914:21)
    at http://null.jsbin.com/runner:75:7```
``````

**Comment by mikechau** [comment]
Hmm.. it works for me. What browser are you using?

**Comment by mikechau** [comment]
Can you click the `HTML` tab, and make sure it looks something like this:

``` HTML
<!DOCTYPE html>
<html>
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<script src="//fb.me/react-with-addons-0.12.2.js"></script>
<script src="//code.jquery.com/jquery.min.js"></script>
  <script src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>

</body>
</html>
```

**Comment by jhgg** [comment]
It's working now o.O
